# ML-03 — Frame Your Lane as an ML Task

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/lucy96039/flyrank-ml-internship/blob/main/work/notebooks/w02_ml_task_framing.ipynb?flush_cache=true)

This skeleton is yours to fill. Work the sections **in order** — each one has a one-line hint. Simple words, honest numbers.

> Working with an AI assistant? Tell it to read `skills/README.md` first and load the one skill this assignment names on its card.

## 1. My lane as an ML task
I frame my Search Performance Optimization lane as a ranking task. The goal is to rank webpages by their priority for improvement, so SEO analysts or website owners can decide which pages to work on first. A ranking approach fits because the decision is not simply whether a page is good or bad; the useful output is an ordered list of pages that need attention.

Decision and action: The output will support the decision of which webpages should be improved first. SEO analysts, digital marketers, or website owners can use the ranked list to prioritize SEO, content, and keyword improvements.

In [24]:
import os

print(os.listdir())

['.config', 'flyrank-ml-internship', 'sample_data']

In [25]:
import os

repo = "/content/flyrank-ml-internship"

print("Repository exists:", os.path.exists(repo))
print("Contents:")
print(os.listdir(repo) if os.path.exists(repo) else "Repository not found")

Repository exists: True
Contents:
['work', 'outputs', 'README.md', '.github', '.gitignore', 'docs', 'data', 'SETUP.md', 'scripts', 'LICENSE', 'submission', 'DATA_USE.md', 'GUIDE.md', 'index.html', 'skills', 'requirements.txt', 'AGENTS.md', '.git', 'notebooks', 'CLAUDE.md']

In [26]:
!git clone https://github.com/krashishkr008-ghg/flyrank-ml-internship.git

fatal: destination path 'flyrank-ml-internship' already exists and is not an empty directory.

In [27]:
import os

repo = "/content/flyrank-ml-internship"

print("Repository exists:", os.path.exists(repo))
print("Repository contents:")
print(os.listdir(repo))

Repository exists: True
Repository contents:
['work', 'outputs', 'README.md', '.github', '.gitignore', 'docs', 'data', 'SETUP.md', 'scripts', 'LICENSE', 'submission', 'DATA_USE.md', 'GUIDE.md', 'index.html', 'skills', 'requirements.txt', 'AGENTS.md', '.git', 'notebooks', 'CLAUDE.md']

In [28]:
print(open("/content/flyrank-ml-internship/skills/README.md").read())

# Skills — the router

This folder is a small library of **skills**: focused instruction files your AI assistant loads
one at a time. One skill per task keeps the assistant sharp — its context window is small, and
filling it with everything makes it worse at the one thing you need.

**How to use it (repo-reading agents — Claude Code, Cursor, Codex):** they find this file
automatically via `AGENTS.md` / `CLAUDE.md`. Just tell your assistant which task you're doing.

**Using a chat-only assistant (ChatGPT / Gemini in a browser)?** Open the skill file on GitHub,
copy its whole content, and paste it into your chat before asking for help. That's it.

## The table — find your task, load ONE skill

| Your task | Load this skill | Also load for data work |
|---|---|---|
| Any task — how to work with your assistant at all | `directing-your-ai-assistant/SKILL.md` | — |
| Pick a lane, frame your question (ML-02, ML-03) | `framing-ml-problems/SKILL.md` | `flyrank/flyrank-data/SKILL.md` |
| Write + verify the data contract (ML-04) | `writing-data-contracts/SKILL.md` | `flyrank/flyrank-data/SKILL.md` |
| Query the big warehouse without downloading it (ML-04/05, capstone) | `querying-big-datasets/SKILL.md` | `flyrank/flyrank-data/SKILL.md` |
| EDA + signal tests with verdicts (ML-06) | `auditing-signals/SKILL.md` | `flyrank/flyrank-data/SKILL.md` |
| Build the rule baseline + ranked queue (ML-07) | `building-baselines/SKILL.md` | `flyrank/flyrank-data/SKILL.md` |
| Train and compare the model (ML-08) | `training-honest-models/SKILL.md` | `flyrank/flyrank-data/SKILL.md` |
| Hunt leakage; validate honestly (ML-05, ML-09) | `hunting-leakage-and-validating/SKILL.md` | `flyrank/flyrank-data/SKILL.md` |
| Write claims that hold (ML-09, ML-10, the paper) | `writing-honest-claims/SKILL.md` | — |
| Write the research paper (ML-11, W7) | `writing-research-papers/SKILL.md` | — |
| Deploy the paper as a page (ML-11) | `deploying-static-pages/SKILL.md` | — |
| Understand FlyRank + the problem (background) | `flyrank/flyrank-context/SKILL.md` | — |

## Reuse this on your next project

Every skill outside `flyrank/` is **general** — take this whole folder to any future project.
Delete `skills/flyrank/` and the flyrank column above, and everything else still works.

In [29]:
import os

skills_path = "/content/flyrank-ml-internship/skills"

for root, dirs, files in os.walk(skills_path):
    for file in files:
        if "framing" in file.lower() or "ml" in file.lower():
            print(os.path.join(root, file))

In [30]:
print(open("/content/flyrank-ml-internship/skills/framing-ml-problems/SKILL.md").read())

---
name: framing-ml-problems
description: Frames a data/ML problem before any modeling — the decision, the action, the cost of a wrong call, task type, target, and success metric. Use when picking a project direction, writing a research question, or mapping a problem onto an ML task type.
---

# Framing ML problems

A model is never the goal. A better DECISION is the goal. Frame first, model later.

## The four questions (answer all four, in writing)

1. **What decision does this improve?** Not "predict X" — decisions. "Which page should an
   editor fix first?" is a decision. "Predict decline" is not, yet.
2. **Who acts on the output, and what do they do?** Name the person and the action. If nobody
   would act differently, the work has no customer.
3. **What does a wrong answer cost?** Wasted editor hours? A missed decline? The cost of errors
   decides how careful the method must be, and which errors matter more.
4. **Why does data or ML help at all?** Sometimes a plain rule (an if-statement) is the right
   answer. Sometimes a dashboard is. ML earns its place only when the pattern is real but too
   messy to write by hand — many signals, tangled, shifting over time.

## Map it to a task type

| If your question sounds like… | Task type | Target | Typical metric |
|---|---|---|---|
| "Which ones first?" | Ranking / scoring | a priority score | precision@K |
| "Will this one decline / recover?" | Classification | a yes/no label from an OBSERVED outcome | ROC-AUC, precision/recall vs base rate |
| "What kinds of items exist?" | Clustering | none (unsupervised) | silhouette + human sense-check |
| "Which signals travel together?" | Signal analysis | none | effect sizes, grouped comparisons |

Two rules that save whole projects:

- **The target must be observed, not defined.** A label that comes from someone's rule means your
  model learns the rule, not the world. Prefer outcomes measured in a later time window.
- **Name the metric before training.** "Good" defined after the fact always looks good.

## Write the one-paragraph frame

> For [who], deciding [what], we will build [output type] from [data], predicting/scoring
> [target] measured by [metric]. A wrong call costs [cost]. A plain rule isn't enough because
> [why]. We will claim only [observed / directional / decision-support] results.

If you can fill that paragraph honestly, you are framed. If a blank stays blank, that blank IS
your next task.

## How to verify

- Show your frame to someone (or your assistant) and ask: "what decision does this improve?"
  If their answer differs from yours, the frame isn't done.
- Check the target: is it observed in the data, or defined by a rule? If defined — reframe.
- Check the metric exists in your data. Can you compute it today, on a baseline? Do it.

In [31]:
print(open("/content/flyrank-ml-internship/skills/flyrank/flyrank-data/SKILL.md").read())

---
name: flyrank-data
description: The FlyRank internship datasets — the 30k-row starter CSV and its gotchas, the ~79M-row warehouse release tables and grains, panel warnings, access, and iteration rules. Load for EVERY task that touches the data. (Project-specific: delete this folder when reusing the skill library elsewhere.)
---

# FlyRank internship data

Two datasets. The small one ships in this repo; the big one is hosted and gated.

## 1. Starter dataset (in this repo)

`data/raw/content_refresh_anonymized.csv` — 30,000 rows × 44 columns, one row per pseudonymized
content item, 32 clients, trailing-90-day metrics. Full column reference: `docs/data-dictionary.md`
(keep it open). The gotchas that cause 90% of mistakes:

- **Rate columns are ×100 percentages**: `ctr = 0.76` means 0.76%, not 76%. Applies to ctr,
  engagement_rate, scroll_rate, ai_traffic_pct, trend_pct.
- **`avg_position = 0` means "no data"**, not rank zero (1,205 rows).
- **`scroll_rate` and `ai_traffic_pct` can exceed 100** — numerator and denominator come from
  different measurement systems. Not a bug; read the dictionary.
- **The label trap:** `is_declining_label` is derived from `trend_direction`, which is computed
  from `trend_pct`. Therefore `trend_direction` and `trend_pct` are NEVER features.
- **Missingness follows content_type** (one type has ~100% missing keyword data; another ~28%
  missing word_count) — a blind fillna(0) injects a category signal. Add has_-flags instead.
- **IDs (`content_id`, `client_id`) are pseudonyms:** grouping/joining/splitting only, never
  features. Use client_id for grouped train/test splits.

## 2. Warehouse release (Hugging Face, gated — instant approval)

`hf://datasets/FlyRank/internship-warehouse` — build v20260703:

| Table | Rows | Grain |
|---|---|---|
| `dim_clients` | 104 | one per pseudonymized client |
| `dim_content` | 519,606 | one per content item |
| `fact_content_daily_performance` | 78,835,655 | report_date × client × content (partitioned by month) |
| `fact_content_daily_performance_sample` | ~11.7M | same grain — careful: this is just the LAST month (June 2026), not a random sample. If your project predicts "what happens next", June is probably your answer key — don't practice on the answer key. Use a middle month instead |
| `fact_content_query_90d` | 2,414,248 | client × content × query hash, fixed 90-day window |

Dates: 2025-01-27 → 2026-06-30 (~17 months). Position column is `gsc_avg_position`.

**Panel warnings (they are real):**
- History depth differs wildly per client — check `dim_clients.gsc_data_start` before defining
  any time window; prefer per-client windows over one global calendar window.
- Rows before a client's `ga4_data_start` have GA4 columns zero-FILLED with
  `ga4_data_available = FALSE` — those zeros mean "not measured", not "no engagement".
  One more trap: the flag isn't just TRUE/FALSE — millions of rows have it NULL (empty).
  Always filter with `ga4_data_available IS TRUE`; writing `= FALSE` or `NOT flag` quietly
  gives wrong counts, because NULL is neither. Same rule for the GSC flag and the client
  access flags in `dim_clients` (10 clients are NULL there).
- A third of clients have little or no usable search/analytics history — expect to filter.
- The query table's per-content context columns repeat on every row: `ANY_VALUE()` them, never
  `SUM()`. Its 90-day window overlaps the snapshot's final months — if your label lives in the
  last 30 days, only `*_prev30`-style columns are safe features (window alignment first!).

**Access + iteration rules:** request gate access once (instant), READ token via getpass or
Colab Secrets — never pasted in a cell (public repo!). While you experiment, query ONE month
from the middle of the data (e.g. `month=2026-03`) — cheap and fast. Don't experiment on the
`_sample` table: it is the final month, and for most projects that month is the "future" your
model gets graded on. Run the full 79M scan only ONCE, when your query is final, and cache the
result to `work/outputs/`. Repeated full scans hit HTTP 429 rate limits.

## How to verify

- Start any session with `COUNT(*)` + `MIN/MAX(report_date)` on your table and match the
  numbers above.
- Grain-probe before aggregating: `GROUP BY <grain cols> HAVING COUNT(*) > 1 LIMIT 5` → empty.
- If a number looks absurd (a 400% rate, a giant ratio from 12 rows), re-read the gotchas
  before celebrating.

In [32]:
import os

repo = "/content/flyrank-ml-internship"

for root, dirs, files in os.walk(repo):
    for file in files:
        if file.endswith((".md", ".ipynb", ".txt")):
            path = os.path.join(root, file)
            try:
                text = open(path, encoding="utf-8", errors="ignore").read()
                if "lane" in text.lower():
                    print("\n---", path, "---")
                    for line in text.splitlines():
                        if "lane" in line.lower():
                            print(line[:300])
            except:
                pass

--- /content/flyrank-ml-internship/README.md ---
| `work/` | **Your space.** Lane experiments and your capstone live here — see `work/README.md`. |
2. **`ml-intern-dataset-and-lane-guide.md`** — how to use the data safely, the capstone workflow, and the analysis "lanes" you can pick from.

--- /content/flyrank-ml-internship/GUIDE.md ---
| `notebooks/03` | Weeks 3+: the **full warehouse release** via DuckDB + Hugging Face | The workflow your lane and capstone run on — aggregate in SQL, model in sklearn |
| `work/` | **Yours.** Lane experiments, capstone notebook, report | Everything you build lives here — start with `work/README.md` |
| `docs/ml-intern-dataset-and-lane-guide.md` | Data safety, the lanes, the capstone workflow | Read in Week 1–2 |
| Weeks 3+ | Learn the full-release workflow (DuckDB over ~79M hosted rows), then your lane | `notebooks/03_working_with_the_full_release.ipynb`, then `work/` (copy pipeline pieces in, don't edit `scripts/`) |
turn" cells (save copies to your repo). Capstone and lane work: **yes** — your own notebooks in

--- /content/flyrank-ml-internship/work/README.md ---
Everything you build lives here: lane experiments, notebooks, figures, and your capstone

--- /content/flyrank-ml-internship/work/capstone_report_template.md ---
# Capstone Report — <your lane>
- **Lane:**
Your method and why it fits the lane. The exact feature list (and what you left out on

--- /content/flyrank-ml-internship/work/notebooks/w05_model.ipynb ---
        "# ML-08 — Capstone Modeling Lane\n",
        "I chose a Random Forest Regressor because my lane is Search Performance Optimization, where the goal is to predict search performance (CTR) from safe features.\n",
        "The split is honest for my Search Performance Optimization lane because the same grouped split is used for both the baseline and the machine learning model. The evaluation is intended for decision-support and avoids data leakage between clients."

--- /content/flyrank-ml-internship/work/notebooks/w01_research_question.ipynb ---
        "# ML-02 — Research Question and Provisional Lane\n",
        "## My Lane\n",
        "I choose the Search Performance Optimization lane. I want to understand how search metrics such as impressions, average position, and click-through rate (CTR) affect webpage performance. This project can help identify pages that need improvement so website owners can make better SEO decisio

--- /content/flyrank-ml-internship/work/notebooks/w02_ml_task_framing.ipynb ---
        "# ML-03 — Frame Your Lane as an ML Task\n",
        "## My Lane as an ML Task\n",
        "**Lane:** Search Performance Optimization\n",
        "I chose the Search Performance Optimization lane. This is a scoring (regression) problem because the goal is to predict a numerical value, such as the click-through rate (CTR) or search performance score of a webpage. These predictions help identify which pages need improvement to increase

--- /content/flyrank-ml-internship/docs/intern-free-tooling-guide.md ---
3. Use Gemini API for model calls only if your lane needs an LLM or embedding-style helper.

--- /content/flyrank-ml-internship/docs/data-dictionary.md ---
The starter CSV above is a 30k-row teaching slice. Lane and capstone work run on the **full

--- /content/flyrank-ml-internship/docs/ml-intern-dataset-and-lane-guide.md ---
# FlyRank ML Internship - Your Dataset and Lane Guide
> approval is instant, so you can get it yourself whenever your lane needs it.
research question -> safe data contract -> signal audit -> baseline score -> your chosen lane -> validation -> ranked action recommendations
### Which Lanes Are Ready, and With What Data
A **lane** is a project direction you can pick. Four lanes are predefined, and freestyle means bringing your own question (section 9 explains it).
| Lane | Type | Default dataset | Output |
| Ranking Signal Analysis | Core lane | warehouse release or starter dataset | Signal report and evidence-backed recommendations |
| Refresh / Content Opportunity Scoring | Core lane | starter playground plus warehouse support | Ranked review queue with scores, actions, and reason codes |
| Structured Content Archetype Clustering | Core lane | warehouse release or starter dataset | Cluster profiles and action mapping; do not call this semantic clustering |
| CTR / Engagement Opportunity Scoring | Core lane | warehouse release or starter dataset | Ranked opportunity score; position/volume adjusted |
(gated; Parquet files; see notebook 03). Ready-made example cuts for each lane live at
[`FlyRank/internship-lanes`](https://huggingface.co/datasets/FlyRank/internship-lanes). Build id:
- The search-performance and lifecycle lanes have the deepest data.
- The CTR and engagement lanes have enough direct signal, but you will still need minimum-volume filters (rules like "only look at pages with at least N impressions") to keep noise out.
## 8. Lane Guide
Whichever lane you pick, you produce the same core artifacts: a data contract, a signal audit, a baseline, a model or analysis, validation, a ranked action output, and a public-safe write-up. These live in your `work/notebooks/` skeletons — one notebook per assignment, already named for you.
### Lane 1: Ranking Signal Analysis
### Lane 2: Refresh / Content Opportunity Scoring
### Lane 3: Structured Content Archetype Clustering
### Lane 4: CTR / Engagement Opportunity Scoring
Freestyle means you skip the four lanes and bring your own search or discoverability question: your own joins, your own features, your own labels, and your own model, built on the full warehouse. No approval, no gate — freestyle is a normal choice, and it follows the same "what done looks like" bar
- cluster stability checks, for archetype lanes — do the clusters survive a re-run?;
- a leakage audit, for every lane, every time.

--- /content/flyrank-ml-internship/skills/README.md ---
| Pick a lane, frame your question (ML-02, ML-03) | `framing-ml-problems/SKILL.md` | `flyrank/flyrank-data/SKILL.md` |

--- /content/flyrank-ml-internship/notebooks/03_working_with_the_full_release.ipynb ---
    "Notebooks 01–02 used the small starter CSV that ships with this repo. Your lane and capstone work\n",
    "The pattern for every lane: **aggregate per content item inside DuckDB**, then hand the small\n",
    "**Where this fits:** every lane brief assumes you can produce per-content feature tables like\n",
    "the one you just built. The lane datasets under the `lanes` HF repo are pre-cut examples of\n",

In [33]:
import os

repo = "/content/flyrank-ml-internship"

for root, dirs, files in os.walk(repo):
    for file in files:
        if file.endswith((".md", ".ipynb", ".txt")):
            path = os.path.join(root, file)
            try:
                text = open(path, encoding="utf-8", errors="ignore").read()
                if "ML-02" in text or "ML-2" in text:
                    print(path)
            except:
                pass

/content/flyrank-ml-internship/README.md
/content/flyrank-ml-internship/work/README.md
/content/flyrank-ml-internship/work/notebooks/w01_research_question.ipynb
/content/flyrank-ml-internship/skills/README.md

In [34]:
import json

path = "/content/flyrank-ml-internship/work/notebooks/w01_research_question.ipynb"

with open(path, "r", encoding="utf-8") as f:
    notebook = json.load(f)

for cell in notebook["cells"]:
    if cell["cell_type"] == "markdown":
        text = "".join(cell["source"])
        if text.strip():
            print("\n" + "="*60)
            print(text)

============================================================
# ML-02 — Research Question and Provisional Lane

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/krashishkr008-ghg/flyrank-ml-internship/blob/main/work/notebooks/w01_research_question.ipynb?flush_cache=true)

This skeleton is yours to fill. Work the sections **in order** — each one has a one-line hint. Simple words, honest numbers.

> Working with an AI assistant? Tell it to read `skills/README.md` first and load the one skill this assignment names on its card.

============================================================
## My Lane

I choose the Search Performance Optimization lane. I want to understand how search metrics such as impressions, average position, and click-through rate (CTR) affect webpage performance. This project can help identify pages that need improvement so website owners can make better SEO decisions. Machine learning may help discover useful patterns in the data.

============================================================
## The Question

**Research Question:** How do average position, impressions, and CTR influence webpage performance?

**Decision:** Identify which webpages should be improved.

**Who takes the action?** SEO analysts, digital marketers, or website owners.

**Action:** Improve SEO, page content, and keywords for underperforming pages.

**Cost of a wrong recommendation:** Optimizing the wrong pages wastes time and resources and may reduce website traffic.

============================================================
## Quick Look at the Data

The starter dataset contains **30,000 rows** and **44 columns**, providing a large amount of information for analysis.

Some important statistics from the dataset are:
- **Average CTR (Click-Through Rate): 0.51**
- **Average Position: 16.34**
- **Average Search Volume: 158.88**

These numbers show that the dataset contains useful search performance metrics and enough variation to study webpage performance. This supports my research question and provides a strong foundation for building data-driven recommendations during the next seven weeks.

============================================================
## 4. Careful words: what I can and can't claim

My work will identify patterns and relationships in the search performance data to support decision-making. It can help suggest which webpages may need improvement based on metrics such as CTR, average position, and search volume.

However, this project cannot prove that one factor directly causes another. It cannot predict Google's search algorithm or guarantee future rankings. The results should be used as decision support rather than as certain or causal conclusions.

============================================================
## Self-check

- [x] Every section above is filled — markdown thinking and the code that backs it.
- [x] The notebook runs top to bottom with no errors (Runtime → Run all).
- [x] No client names, URLs, or private queries are included.
- [x] My claims use careful words: observed, measured, directional, and decision-support.
- [x] The notebook is committed to my repository under `work/notebooks/` and is ready for submission.

## 2. Target or proxy

I would use an observed search-performance outcome as the target. The target should represent whether a webpage shows weaker performance in a later observed period, rather than being a label created directly from the same features used for prediction. For this starter-data framing, I will use the observed engagement outcome as a proxy for page performance. The target should be measured after the input metrics so that the model learns from earlier signals to support a later decision.

In [35]:
import pandas as pd

data_path = "/content/flyrank-ml-internship/data/raw/content_refresh_anonymized.csv"

df = pd.read_csv(data_path)

print("Shape:", df.shape)
print("\nColumns:")
print(df.columns.tolist())

Shape: (30000, 44)

Columns:
['content_id', 'client_id', 'search_volume', 'competition', 'competition_level', 'cpc', 'content_type', 'main_intent', 'word_count', 'char_count', 'provider_used', 'model_used', 'impressions_90d', 'clicks_90d', 'pageviews_90d', 'sessions_90d', 'users_90d', 'engaged_sessions_90d', 'ai_sessions_90d', 'scroll_events_90d', 'days_with_impressions', 'days_with_sessions', 'impressions_last_30d', 'clicks_last_30d', 'sessions_last_30d', 'impressions_prev_30d', 'clicks_prev_30d', 'sessions_prev_30d', 'content_age_days', 'age_tier', 'age_tier_order', 'days_since_last_update', 'freshness_tier', 'word_count_tier', 'char_count_tier', 'ctr', 'avg_position', 'engagement_rate', 'scroll_rate', 'ai_traffic_pct', 'impression_tier', 'position_tier', 'trend_direction', 'trend_pct']

## 3. Success metric

My primary success metric will be Precision@K. The model is useful if a high proportion of the top-ranked webpages are genuinely useful pages to prioritize for improvement. I would choose a practical K, such as the top 50 pages, because an SEO team has limited time and cannot act on every webpage at once. The metric should be evaluated against an observed later outcome.

In [36]:
K = 50

print("Planned evaluation metric: Precision@K")
print("K =", K)
print("Interpretation: How many of the top", K, "ranked pages are relevant for improvement?")

Planned evaluation metric: Precision@K
K = 50
Interpretation: How many of the top 50 ranked pages are relevant for improvement?

## 4. The unit of analysis, as a real dataframe
The unit of analysis is one pseudonymized content item (webpage). Each row represents one webpage and contains its search, content, and performance measurements. The starter dataset has 30,000 content items and 44 columns. The content_id identifies the item, while client_id identifies the associated pseudonymized client and is used for grouping rather than as a prediction feature.

In [37]:
display(df.head(10))

print("Number of rows:", len(df))
print("Number of columns:", len(df.columns))

,content_id,client_id,search_volume,competition,competition_level,cpc,content_type,main_intent,word_count,char_count,...,char_count_tier,ctr,avg_position,engagement_rate,scroll_rate,ai_traffic_pct,impression_tier,position_tier,trend_direction,trend_pct
0,content_304f48230142,client_f369cb89fc,10.0,0.67,HIGH,2.05,keyword article,transactional,3221.0,20457.0,...,15000-25000,0.76,10.6,5.88,4.55,0.0,good,striking,down,-41.4
1,content_a1fb4e703a9e,client_4e07408562,90.0,0.01,LOW,0.05,keyword article,informational,2481.0,15562.0,...,15000-25000,0.05,20.3,0.00,10.00,0.0,good,page_3_5,down,-57.7
2,content_9aa793d4d895,client_7f2253d7e2,0.0,0.00,LOW,0.00,keyword article,informational,3515.0,23643.0,...,15000-25000,0.09,36.5,0.00,28.57,0.0,good,page_3_5,down,-60.9
3,content_331d6c4de07b,client_19581e27de,10.0,0.00,LOW,0.00,keyword article,commercial,NaN,NaN,...,NaN,0.49,6.2,1.28,3.45,0.0,good,page_1,stable,-13.8
4,content_d99b7a2d90ca,client_3fdba35f04,0.0,0.00,LOW,0.00,keyword article,informational,2803.0,17469.0,...,15000-25000,0.13,44.0,0.00,24.29,0.0,good,page_3_5,down,-34.7
5,content_d4084a4bc775,client_f369cb89fc,720.0,1.00,HIGH,1.05,keyword article,transactional,3080.0,18178.0,...,15000-25000,0.03,8.5,0.00,25.00,0.0,good,page_1,down,-38.9
6,content_9a34b442b552,client_8722616204,0.0,0.00,LOW,0.00,keyword article,informational,3059.0,20810.0,...,15000-25000,0.00,7.0,0.00,0.00,0.0,low,page_1,down,-92.3
7,content_a63219c6e95a,client_19581e27de,590.0,0.44,MEDIUM,0.64,keyword article,commercial,NaN,NaN,...,NaN,0.06,21.2,3.57,7.14,0.0,moderate,page_3_5,stable,0.6
8,content_5e6c160719bc,client_6208ef0f77,0.0,0.00,LOW,0.00,keyword article,informational,3807.0,24228.0,...,15000-25000,0.09,46.0,5.88,6.25,0.0,excellent,page_3_5,down,-58.8
9,content_c27558df2b0c,client_19581e27de,0.0,0.00,LOW,0.00,keyword article,informational,NaN,NaN,...,NaN,0.16,4.9,0.00,0.00,0.0,moderate,page_1,down,-29.2

Number of rows: 30000
Number of columns: 44

In [38]:
# Show a small slice of the actual dataframe
display(df.head(10))

print("Number of rows:", len(df))
print("Number of columns:", len(df.columns))

,content_id,client_id,search_volume,competition,competition_level,cpc,content_type,main_intent,word_count,char_count,...,char_count_tier,ctr,avg_position,engagement_rate,scroll_rate,ai_traffic_pct,impression_tier,position_tier,trend_direction,trend_pct
0,content_304f48230142,client_f369cb89fc,10.0,0.67,HIGH,2.05,keyword article,transactional,3221.0,20457.0,...,15000-25000,0.76,10.6,5.88,4.55,0.0,good,striking,down,-41.4
1,content_a1fb4e703a9e,client_4e07408562,90.0,0.01,LOW,0.05,keyword article,informational,2481.0,15562.0,...,15000-25000,0.05,20.3,0.00,10.00,0.0,good,page_3_5,down,-57.7
2,content_9aa793d4d895,client_7f2253d7e2,0.0,0.00,LOW,0.00,keyword article,informational,3515.0,23643.0,...,15000-25000,0.09,36.5,0.00,28.57,0.0,good,page_3_5,down,-60.9
3,content_331d6c4de07b,client_19581e27de,10.0,0.00,LOW,0.00,keyword article,commercial,NaN,NaN,...,NaN,0.49,6.2,1.28,3.45,0.0,good,page_1,stable,-13.8
4,content_d99b7a2d90ca,client_3fdba35f04,0.0,0.00,LOW,0.00,keyword article,informational,2803.0,17469.0,...,15000-25000,0.13,44.0,0.00,24.29,0.0,good,page_3_5,down,-34.7
5,content_d4084a4bc775,client_f369cb89fc,720.0,1.00,HIGH,1.05,keyword article,transactional,3080.0,18178.0,...,15000-25000,0.03,8.5,0.00,25.00,0.0,good,page_1,down,-38.9
6,content_9a34b442b552,client_8722616204,0.0,0.00,LOW,0.00,keyword article,informational,3059.0,20810.0,...,15000-25000,0.00,7.0,0.00,0.00,0.0,low,page_1,down,-92.3
7,content_a63219c6e95a,client_19581e27de,590.0,0.44,MEDIUM,0.64,keyword article,commercial,NaN,NaN,...,NaN,0.06,21.2,3.57,7.14,0.0,moderate,page_3_5,stable,0.6
8,content_5e6c160719bc,client_6208ef0f77,0.0,0.00,LOW,0.00,keyword article,informational,3807.0,24228.0,...,15000-25000,0.09,46.0,5.88,6.25,0.0,excellent,page_3_5,down,-58.8
9,content_c27558df2b0c,client_19581e27de,0.0,0.00,LOW,0.00,keyword article,informational,NaN,NaN,...,NaN,0.16,4.9,0.00,0.00,0.0,moderate,page_1,down,-29.2

Number of rows: 30000
Number of columns: 44

In [39]:
display(df.head(10))

print("Number of rows:", len(df))
print("Number of columns:", len(df.columns))

,content_id,client_id,search_volume,competition,competition_level,cpc,content_type,main_intent,word_count,char_count,...,char_count_tier,ctr,avg_position,engagement_rate,scroll_rate,ai_traffic_pct,impression_tier,position_tier,trend_direction,trend_pct
0,content_304f48230142,client_f369cb89fc,10.0,0.67,HIGH,2.05,keyword article,transactional,3221.0,20457.0,...,15000-25000,0.76,10.6,5.88,4.55,0.0,good,striking,down,-41.4
1,content_a1fb4e703a9e,client_4e07408562,90.0,0.01,LOW,0.05,keyword article,informational,2481.0,15562.0,...,15000-25000,0.05,20.3,0.00,10.00,0.0,good,page_3_5,down,-57.7
2,content_9aa793d4d895,client_7f2253d7e2,0.0,0.00,LOW,0.00,keyword article,informational,3515.0,23643.0,...,15000-25000,0.09,36.5,0.00,28.57,0.0,good,page_3_5,down,-60.9
3,content_331d6c4de07b,client_19581e27de,10.0,0.00,LOW,0.00,keyword article,commercial,NaN,NaN,...,NaN,0.49,6.2,1.28,3.45,0.0,good,page_1,stable,-13.8
4,content_d99b7a2d90ca,client_3fdba35f04,0.0,0.00,LOW,0.00,keyword article,informational,2803.0,17469.0,...,15000-25000,0.13,44.0,0.00,24.29,0.0,good,page_3_5,down,-34.7
5,content_d4084a4bc775,client_f369cb89fc,720.0,1.00,HIGH,1.05,keyword article,transactional,3080.0,18178.0,...,15000-25000,0.03,8.5,0.00,25.00,0.0,good,page_1,down,-38.9
6,content_9a34b442b552,client_8722616204,0.0,0.00,LOW,0.00,keyword article,informational,3059.0,20810.0,...,15000-25000,0.00,7.0,0.00,0.00,0.0,low,page_1,down,-92.3
7,content_a63219c6e95a,client_19581e27de,590.0,0.44,MEDIUM,0.64,keyword article,commercial,NaN,NaN,...,NaN,0.06,21.2,3.57,7.14,0.0,moderate,page_3_5,stable,0.6
8,content_5e6c160719bc,client_6208ef0f77,0.0,0.00,LOW,0.00,keyword article,informational,3807.0,24228.0,...,15000-25000,0.09,46.0,5.88,6.25,0.0,excellent,page_3_5,down,-58.8
9,content_c27558df2b0c,client_19581e27de,0.0,0.00,LOW,0.00,keyword article,informational,NaN,NaN,...,NaN,0.16,4.9,0.00,0.00,0.0,moderate,page_1,down,-29.2

Number of rows: 30000
Number of columns: 44

In [40]:
# Sketch of the target column we would create from a later observed period

target_sketch = df[["content_id", "client_id"]].head(10).copy()

target_sketch["future_underperformance"] = pd.NA

display(target_sketch)

             content_id          client_id future_underperformance
0  content_304f48230142  client_f369cb89fc                    <NA>
1  content_a1fb4e703a9e  client_4e07408562                    <NA>
2  content_9aa793d4d895  client_7f2253d7e2                    <NA>
3  content_331d6c4de07b  client_19581e27de                    <NA>
4  content_d99b7a2d90ca  client_3fdba35f04                    <NA>
5  content_d4084a4bc775  client_f369cb89fc                    <NA>
6  content_9a34b442b552  client_8722616204                    <NA>
7  content_a63219c6e95a  client_19581e27de                    <NA>
8  content_5e6c160719bc  client_6208ef0f77                    <NA>
9  content_c27558df2b0c  client_19581e27de                    <NA>

In [41]:
K = 50

print("Planned evaluation metric: Precision@K")
print("K =", K)
print("Interpretation: How many of the top", K, "ranked pages are relevant for improvement?")

Planned evaluation metric: Precision@K
K = 50
Interpretation: How many of the top 50 ranked pages are relevant for improvement?

## 5. Why ML beats a fixed rule here
A fixed rule such as "improve every page with CTR below a certain threshold" would be too simple because webpage performance depends on several signals, including impressions, average position, CTR, engagement rate, content characteristics, and search demand. These signals can interact, and the useful patterns may differ across webpages. ML can combine multiple observed signals to produce a priority ranking instead of relying on one manually chosen threshold. The output would be used as decision support to help SEO analysts prioritize which webpages to improve first, not as a guarantee of future search performance.

Self-check
Before you submit, confirm each line honestly:

1 Every section above is filled — markdown thinking AND the code that backs it
2 The notebook runs top to bottom with no errors (Runtime → Run all)
3 No client names, URLs, or private queries anywhere
4 My claims use careful words: observed, measured, directional, decision-support
5 Committed to my repo under work/notebooks/ — then submit your repo URL on the card. Done.

In [42]:
print("Notebook framing check")
print("Task type: Ranking")
print("Unit of analysis: One content item / webpage")
print("Metric: Precision@50")
print("Data shape:", df.shape)

Notebook framing check
Task type: Ranking
Unit of analysis: One content item / webpage
Metric: Precision@50
Data shape: (30000, 44)